namespace O {
	namespace BaseNetworkable {
		constexpr auto JustCreatedk__BackingField = 0x20;
		constexpr auto entityDestroy = 0x28;
		constexpr auto prefabID = 0x30;
		constexpr auto globalBroadcast = 0x34;
		constexpr auto globalBuildingBlock = 0x35;
		constexpr auto net = 0x38;
		constexpr auto IsDestroyedk__BackingField = 0x40;
		constexpr auto _prefabName = 0x48;
		constexpr auto _prefabNameWithoutExtension = 0x50;
		constexpr auto clientEntities = 0x0;
		constexpr auto isServersideEntity = 0x0;
		constexpr auto postNetworkUpdateComponents = 0x58;
		constexpr auto parentEntity = 0x60;
		constexpr auto children = 0x70;
		constexpr auto canTriggerParent = 0x78;
	};
	namespace BasePlayer {
		constexpr auto __menuOption_Climb = 0x280;
		constexpr auto __menuOption_Drink = 0x2F0;
		constexpr auto __menuOption_InviteToClan = 0x360;
		constexpr auto __menuOption_InviteToTeam = 0x3D0;
		constexpr auto __menuOption_Menu_AssistPlayer = 0x440;
		constexpr auto __menuOption_Menu_LootPlayer = 0x4B0;
		constexpr auto __menuOption_SaltWater = 0x520;
		constexpr auto ClanInviteSuccess = 0x0;
		constexpr auto ClanInviteFailure = 0x8;
		constexpr auto ClanInviteFull = 0x10;
		constexpr auto clanId = 0x590;
		constexpr auto playerModel = 0x598;
		constexpr auto Frozen = 0x5A0;
		constexpr auto LookLocked = 0x5A1;
		constexpr auto voiceRecorder = 0x5A8;
		constexpr auto voiceSpeaker = 0x5B0;
		constexpr auto input = 0x5B8;
		constexpr auto movement = 0x5C0;
		constexpr auto collision = 0x5C8;
		constexpr auto bagCount = 0x5D0;
		constexpr auto shelterCount = 0x5D4;
		constexpr auto emptyState = 0x18;
		constexpr auto modelInitUnderwear = 0x5D8;
		constexpr auto _lookingAt = 0x5E0;
		constexpr auto _lookingAtEntity = 0x5E8;
		constexpr auto _lookingAtCollider = 0x5F0;
		constexpr auto lookingAtPointk__BackingField = 0x5F8;
		constexpr auto playerModelPrefab = 0x0;
		constexpr auto playerCollisionPrefab = 0x0;
		constexpr auto wakeTime = 0x604;
		constexpr auto needsClothesRebuild = 0x608;
		constexpr auto wasSleeping = 0x609;
		constexpr auto wokeUpBefore = 0x60A;
		constexpr auto wasDead = 0x60B;
		constexpr auto HasMountedClothingk__BackingField = 0x60C;
		constexpr auto HasWearableClothingk__BackingField = 0x60D;
		constexpr auto lastClothesHash = 0x610;
		constexpr auto visiblePlayerList = 0x20;
		constexpr auto craftMode = 0x28;
		constexpr auto lootPanelOverride = 0x30;
		constexpr auto lastOpenSoundPlay = 0x614;
		constexpr auto currentViewMode = 0x618;
		constexpr auto selectedViewMode = 0x61C;
		constexpr auto lastRevivePoint = 0x620;
		constexpr auto lastReviveDirection = 0x62C;
		constexpr auto IsWearingDiveGogglesk__BackingField = 0x638;
		constexpr auto GestureViewModel = 0x640;
		constexpr auto INTERACTION_TICK_RATE = 0x0;
		constexpr auto currentClientRespawnInformation = 0x648;
		constexpr auto respawnOptionsTimestamp = 0x650;
		constexpr auto lastParachuteRequest = 0x654;
		constexpr auto timeSinceUpdatedLookingAt = 0x658;
		constexpr auto nextTopologyTestTime = 0x65C;
		constexpr auto usePressTime = 0x660;
		constexpr auto useHeldTime = 0x664;
		constexpr auto lookingAtTest = 0x668;
		constexpr auto lastDeathTimeClient = 0x38;
		constexpr auto _localTransferProtectionExpires = 0x3C;
		constexpr auto drinkRange = 0x0;
		constexpr auto drinkMovementSpeed = 0x0;
		constexpr auto cachedWaterDrinkingPoint = 0x670;
		constexpr auto hasRequestedServerEmoji = 0x67C;
		constexpr auto outstandingEmojiRequests = 0x680;
		constexpr auto timeGatedEmojiRequests = 0x688;
		constexpr auto GestureCancelString = 0x0;
		constexpr auto gestureList = 0x690;
		constexpr auto gestureFinishedTime = 0x698;
		constexpr auto blockHeldInputTimer = 0x69C;
		constexpr auto currentGesture = 0x6A0;
		constexpr auto disabledHeldEntity = 0x6A8;
		constexpr auto nextGestureMenuOpenTime = 0x6B0;
		constexpr auto lastGestureCancel = 0x6B4;
		constexpr auto client_lastHelloTime = 0x6B8;
		constexpr auto currentTeam = 0x6C0;
		constexpr auto MaxTeamSizeToast = 0x40;
		constexpr auto clientTeam = 0x6C8;
		constexpr auto lastReceivedTeamTime = 0x6D0;
		constexpr auto lastPresenceTeamId = 0x6D8;
		constexpr auto lastPresenceTeamSize = 0x6E0;
		constexpr auto playerGroupKey = 0x6E8;
		constexpr auto playerGroupSizeKey = 0x6F0;
		constexpr auto clActiveItem = 0x6F8;
		constexpr auto MarkerLimitPhrase = 0x48;
		constexpr auto MaxMapNoteLabelLength = 0x0;
		constexpr auto ClientCurrentMapNotes = 0x700;
		constexpr auto ClientCurrentDeathNote = 0x708;
		constexpr auto keepOpenMapInterface = 0x710;
		constexpr auto missions = 0x718;
		constexpr auto _activeMission = 0x720;
		constexpr auto modelState = 0x728;
		constexpr auto mounted = 0x730;
		constexpr auto nextSeatSwapTime = 0x740;
		constexpr auto mountInputHeldDuringDismount = 0x744;
		constexpr auto PetEntity = 0x748;
		constexpr auto lastPetCommandIssuedTime = 0x750;
		constexpr auto PetPrefabID = 0x754;
		constexpr auto PetID = 0x758;
		constexpr auto PetWheelHasBeenOpened = 0x50;
		constexpr auto HostileTitle = 0x58;
		constexpr auto HostileDesc = 0x60;
		constexpr auto HostileMarker = 0x68;
		constexpr auto GoToTitle = 0x88;
		constexpr auto GoToDesc = 0x90;
		constexpr auto GoToMarker = 0x98;
		constexpr auto DollarTitle = 0xB8;
		constexpr auto DollarDesc = 0xC0;
		constexpr auto DollarMarker = 0xC8;
		constexpr auto LootTitle = 0xE8;
		constexpr auto LootDesc = 0xF0;
		constexpr auto LootMarker = 0xF8;
		constexpr auto NodeTitle = 0x118;
		constexpr auto NodeDesc = 0x120;
		constexpr auto NodeMarker = 0x128;
		constexpr auto GunTitle = 0x148;
		constexpr auto GunDesc = 0x150;
		constexpr auto GunMarker = 0x158;
		constexpr auto BuildMarker = 0x178;
		constexpr auto RadialPings = 0x198;
		constexpr auto ClientCurrentPings = 0x760;
		constexpr auto doubleTapThreshold = 0x0;
		constexpr auto tapInProcess = 0x768;
		constexpr auto lastPingTap = 0x76C;
		constexpr auto cachedBuildingPrivilegeTime = 0x770;
		constexpr auto cachedBuildingPrivilege = 0x778;
		constexpr auto cachedVehicleBuildingBlockedTime = 0x780;
		constexpr auto cachedVehicleBuildingBlocked = 0x784;
		constexpr auto cachedEntityBuildingBlockedTime = 0x788;
		constexpr auto cachedEntityBuildingBlocked = 0x78C;
		constexpr auto cachedPrivilegeFromOther = 0x790;
		constexpr auto cachedPrivilegeFromOtherTime = 0x798;
		constexpr auto maxProjectileID = 0x79C;
		constexpr auto WILDERNESS = 0x0;
		constexpr auto MONUMENT = 0x0;
		constexpr auto BASE = 0x0;
		constexpr auto FLYING = 0x0;
		constexpr auto BOATING = 0x0;
		constexpr auto SWIMMING = 0x0;
		constexpr auto DRIVING = 0x0;
		constexpr auto lastSpectateCameraUpdate = 0x7A0;
		constexpr auto currentSpectateTeamInfo = 0x1A0;
		constexpr auto memberBuffer = 0x1A8;
		constexpr auto filterSpectateMapTeamID = 0x1B0;
		constexpr auto lastReceivedSpectateTeamInfo = 0x1B4;
		constexpr auto lastUpdateTime = 0x7A4;
		constexpr auto cachedThreatLevel = 0x7A8;
		constexpr auto serverTickRateDefault = 0x0;
		constexpr auto clientTickRateDefault = 0x0;
		constexpr auto serverTickRate = 0x7AC;
		constexpr auto clientTickRate = 0x7B0;
		constexpr auto serverTickInterval = 0x7B4;
		constexpr auto clientTickInterval = 0x7B8;
		constexpr auto lastSentTickTime = 0x7BC;
		constexpr auto lastTickStopwatch = 0x7C0;
		constexpr auto lastSentTick = 0x7C8;
		constexpr auto CurrentTutorialAllowancek__BackingField = 0x7D0;
		constexpr auto startTutorialCooldown = 0x7D4;
		constexpr auto nextVisThink = 0x7D8;
		constexpr auto lastTimeSeen = 0x7DC;
		constexpr auto debugPrevVisible = 0x7E0;
		constexpr auto MaxBotIdRange = 0x0;
		constexpr auto fallDamageEffect = 0x7E8;
		constexpr auto drownEffect = 0x7F0;
		constexpr auto playerFlags = 0x7F8;
		constexpr auto eyes = 0x800;
		constexpr auto inventory = 0x808;
		constexpr auto blueprints = 0x810;
		constexpr auto metabolism = 0x818;
		constexpr auto modifiers = 0x820;
		constexpr auto playerCollider = 0x828;
		constexpr auto Belt = 0x830;
		constexpr auto playerRigidbody = 0x838;
		constexpr auto userID = 0x840;
		constexpr auto UserIDString = 0x848;
		constexpr auto gamemodeteam = 0x850;
		constexpr auto reputation = 0x854;
		constexpr auto _displayName = 0x858;
		constexpr auto _lastSetName = 0x860;
		constexpr auto crouchSpeed = 0x0;
		constexpr auto walkSpeed = 0x0;
		constexpr auto runSpeed = 0x0;
		constexpr auto crawlSpeed = 0x0;
		constexpr auto playerColliderStanding = 0x868;
		constexpr auto playerColliderDucked = 0x87C;
		constexpr auto playerColliderCrawling = 0x890;
		constexpr auto playerColliderLyingDown = 0x8A4;
		constexpr auto cachedProtection = 0x8B8;
		constexpr auto oldCameraFix = 0x1B8;
		constexpr auto lastHeadshotSoundTime = 0x8C0;
		constexpr auto nextColliderRefreshTime = 0x8C4;
		constexpr auto weaponMoveSpeedScale = 0x8C8;
		constexpr auto clothingBlocksAiming = 0x8CC;
		constexpr auto clothingMoveSpeedReduction = 0x8D0;
		constexpr auto clothingWaterSpeedBonus = 0x8D4;
		constexpr auto clothingAccuracyBonus = 0x8D8;
		constexpr auto equippingBlocked = 0x8DC;
		constexpr auto eggVision = 0x8E0;
		constexpr auto activeTelephone = 0x8E8;
		constexpr auto designingAIEntity = 0x8F0;
	};
	namespace BaseMovement {
		constexpr auto adminCheat = 0x20;
		constexpr auto adminSpeed = 0x24;
		constexpr auto Ownerk__BackingField = 0x28;
		constexpr auto InheritedVelocityk__BackingField = 0x30;
		constexpr auto TargetMovementk__BackingField = 0x3C;
		constexpr auto Runningk__BackingField = 0x48;
		constexpr auto Duckingk__BackingField = 0x4C;
		constexpr auto Crawlingk__BackingField = 0x50;
		constexpr auto Groundedk__BackingField = 0x54;
		constexpr auto RECENTLY_TELEPORTED_TIME = 0x0;
		constexpr auto lastTeleportedTime = 0x58;
	};
	namespace BaseProjectile {
		constexpr auto NoiseRadius = 0x298;
		constexpr auto damageScale = 0x29C;
		constexpr auto distanceScale = 0x2A0;
		constexpr auto projectileVelocityScale = 0x2A4;
		constexpr auto automatic = 0x2A8;
		constexpr auto usableByTurret = 0x2A9;
		constexpr auto turretDamageScale = 0x2AC;
		constexpr auto attackFX = 0x2B0;
		constexpr auto silencedAttack = 0x2B8;
		constexpr auto muzzleBrakeAttack = 0x2C0;
		constexpr auto MuzzlePoint = 0x2C8;
		constexpr auto reloadTime = 0x2D0;
		constexpr auto canUnloadAmmo = 0x2D4;
		constexpr auto primaryMagazine = 0x2D8;
		constexpr auto fractionalReload = 0x2E0;
		constexpr auto reloadStartDuration = 0x2E4;
		constexpr auto reloadFractionDuration = 0x2E8;
		constexpr auto reloadEndDuration = 0x2EC;
		constexpr auto aimSway = 0x2F0;
		constexpr auto aimSwaySpeed = 0x2F4;
		constexpr auto recoil = 0x2F8;
		constexpr auto aimconeCurve = 0x300;
		constexpr auto aimCone = 0x308;
		constexpr auto hipAimCone = 0x30C;
		constexpr auto aimconePenaltyPerShot = 0x310;
		constexpr auto aimConePenaltyMax = 0x314;
		constexpr auto aimconePenaltyRecoverTime = 0x318;
		constexpr auto aimconePenaltyRecoverDelay = 0x31C;
		constexpr auto stancePenaltyScale = 0x320;
		constexpr auto hasADS = 0x324;
		constexpr auto noAimingWhileCycling = 0x325;
		constexpr auto manualCycle = 0x326;
		constexpr auto needsCycle = 0x327;
		constexpr auto isCycling = 0x328;
		constexpr auto aiming = 0x329;
		constexpr auto useEmptyAmmoState = 0x32A;
		constexpr auto isBurstWeapon = 0x32B;
		constexpr auto canChangeFireModes = 0x32C;
		constexpr auto defaultOn = 0x32D;
		constexpr auto internalBurstRecoilScale = 0x330;
		constexpr auto internalBurstFireRateScale = 0x334;
		constexpr auto internalBurstAimConeScale = 0x338;
		constexpr auto resetDuration = 0x33C;
		constexpr auto numShotsFired = 0x340;
		constexpr auto maxDistance = 0x0;
		constexpr auto nextReloadTime = 0x344;
		constexpr auto startReloadTime = 0x348;
		constexpr auto stancePenalty = 0x34C;
		constexpr auto aimconePenalty = 0x350;
		constexpr auto cachedModHash = 0x354;
		constexpr auto sightAimConeScale = 0x358;
		constexpr auto sightAimConeOffset = 0x35C;
		constexpr auto hipAimConeScale = 0x360;
		constexpr auto hipAimConeOffset = 0x364;
		constexpr auto Param_Ammo_True = 0x0;
		constexpr auto Param_Ammo_False = 0x4;
		constexpr auto isReloading = 0x368;
		constexpr auto timeSinceReloadFinished = 0x36C;
		constexpr auto swaySampleTime = 0x370;
		constexpr auto lastShotTime = 0x374;
		constexpr auto reloadPressTime = 0x378;
		constexpr auto ammoTypePreReload = 0x380;
		constexpr auto fractionalReloadDesiredCount = 0x388;
		constexpr auto fractionalReloadNumAdded = 0x38C;
		constexpr auto currentBurst = 0x390;
		constexpr auto triggerReady = 0x394;
		constexpr auto nextHeightCheckTime = 0x398;
		constexpr auto cachedUnderground = 0x39C;
		constexpr auto createdProjectiles = 0x3A0;
	};
	namespace PlayerWalkMovement {
		constexpr auto WaterLevelHead = 0x0;
		constexpr auto WaterLevelNeck = 0x0;
		constexpr auto zeroFrictionMaterial = 0x60;
		constexpr auto highFrictionMaterial = 0x68;
		constexpr auto capsuleHeight = 0x70;
		constexpr auto capsuleCenter = 0x74;
		constexpr auto capsuleHeightDucked = 0x78;
		constexpr auto capsuleCenterDucked = 0x7C;
		constexpr auto capsuleHeightCrawling = 0x80;
		constexpr auto capsuleCenterCrawling = 0x84;
		constexpr auto gravityTestRadius = 0x88;
		constexpr auto gravityMultiplier = 0x8C;
		constexpr auto gravityMultiplierSwimming = 0x90;
		constexpr auto maxAngleWalking = 0x94;
		constexpr auto maxAngleClimbing = 0x98;
		constexpr auto maxAngleSliding = 0x9C;
		constexpr auto maxStepHeight = 0xA0;
		constexpr auto body = 0xA8;
		constexpr auto initialColDetectionMode = 0xB0;
		constexpr auto capsule = 0xB8;
		constexpr auto ladder = 0xC0;
		constexpr auto maxVelocity = 0xC8;
		constexpr auto groundAngle = 0xCC;
		constexpr auto groundAngleNew = 0xD0;
		constexpr auto groundTime = 0xD4;
		constexpr auto jumpTime = 0xD8;
		constexpr auto landTime = 0xDC;
		constexpr auto previousPosition = 0xE0;
		constexpr auto previousVelocity = 0xEC;
		constexpr auto previousInheritedVelocity = 0xF8;
		constexpr auto groundNormal = 0x104;
		constexpr auto groundNormalNew = 0x110;
		constexpr auto groundVelocity = 0x11C;
		constexpr auto groundVelocityNew = 0x128;
		constexpr auto nextSprintTime = 0x134;
		constexpr auto lastSprintTime = 0x138;
		constexpr auto sprintForced = 0x13C;
		constexpr auto attemptedMountTime = 0x140;
		constexpr auto modify = 0x144;
		constexpr auto grounded = 0x148;
		constexpr auto climbing = 0x149;
		constexpr auto sliding = 0x14A;
		constexpr auto swimming = 0x14B;
		constexpr auto wasSwimming = 0x14C;
		constexpr auto jumping = 0x14D;
		constexpr auto wasJumping = 0x14E;
		constexpr auto falling = 0x14F;
		constexpr auto wasFalling = 0x150;
		constexpr auto flying = 0x151;
		constexpr auto wasFlying = 0x152;
		constexpr auto forcedDuckDelta = 0x154;
	};
	namespace UnityEngine_GUI {
		constexpr auto s_BoxHash = 0x4;//íå íà àâòîäàìïå
		constexpr auto s_ButonHash = 0x8;//íå íà àâòîäàìïå
		constexpr auto s_RepeatButtonHash = 0xc;//íå íà àâòîäàìïå
		constexpr auto s_ToggleHash = 0x10;//íå íà àâòîäàìïå
		constexpr auto s_ButtonGridHash = 0x14;//íå íà àâòîäàìïå
		constexpr auto s_SliderHash = 0x18;//íå íà àâòîäàìïå
		constexpr auto s_BeginGroupHash = 0x1c;//íå íà àâòîäàìïå
		constexpr auto s_ScrollviewHash = 0x20;//íå íà àâòîäàìïå
		constexpr auto scrollTroughSidek__BackingField = 0x24;//íå íà àâòîäàìïå
		constexpr auto nextScrollStepTimek__BackingField = 0x28;//íå íà àâòîäàìïå
		constexpr auto s_Skin = 0x30;//íå íà àâòîäàìïå
		constexpr auto s_ToolTipRect = 0x38;//íå íà àâòîäàìïå
		constexpr auto scrollViewStatesk__BackingField = 0x48;//íå íà àâòîäàìïå
	};
	namespace UnityEngine_GUIStyle {
		constexpr auto m_Ptr = 0x10;//íå íà àâòîäàìïå
		constexpr auto m_Normal = 0x18;//íå íà àâòîäàìïå
		constexpr auto m_Hover = 0x20;//íå íà àâòîäàìïå
		constexpr auto m_Active = 0x28;//íå íà àâòîäàìïå
		constexpr auto m_Focused = 0x30;//íå íà àâòîäàìïå
		constexpr auto m_OnNormal = 0x38;//íå íà àâòîäàìïå
		constexpr auto m_OnHover = 0x40;//íå íà àâòîäàìïå
		constexpr auto m_OnActive = 0x48;//íå íà àâòîäàìïå
		constexpr auto m_OnFocused = 0x50;//íå íà àâòîäàìïå
		constexpr auto m_Border = 0x58;//íå íà àâòîäàìïå
		constexpr auto m_Padding = 0x60;//íå íà àâòîäàìïå
		constexpr auto m_Margin = 0x68;//íå íà àâòîäàìïå
		constexpr auto m_Overflow = 0x70;//íå íà àâòîäàìïå
		constexpr auto m_Name = 0x78;//íå íà àâòîäàìïå
		constexpr auto s_None = 0x8;//íå íà àâòîäàìïå
	};
	namespace UnityEngine_Event {
		constexpr auto m_Ptr = 0x10;//íå íà àâòîäàìïå
		constexpr auto s_MasterEvent = 0x8;//íå íà àâòîäàìïå
	};
	namespace UnityEngine_DDraw {
		constexpr auto singleton = 0x8;//íå íà àâòîäàìïå
		constexpr auto list = 0x18;//íå íà àâòîäàìïå
		constexpr auto AutoYPosition = 0x10;//íå íà àâòîäàìïå
		constexpr auto LastAutoY = 0x14;//íå íà àâòîäàìïå
		constexpr auto lineMaterial = 0x18;//íå íà àâòîäàìïå
		constexpr auto _skin = 0x20;//íå íà àâòîäàìïå
	};
	namespace ModelState {
		constexpr auto waterLevel = 0x10;
		constexpr auto lookDir = 0x14;
		constexpr auto flags = 0x20;
		constexpr auto poseType = 0x24;
		constexpr auto inheritedVelocity = 0x28;
		constexpr auto ladderType = 0x34;
		constexpr auto ShouldPool = 0x38;
		constexpr auto _disposed = 0x39;
	};
	namespace ProtoBuf_PlayerProjectileUpdate {
		constexpr auto projectileID = 0x10;//íå íà àâòîäàìïå
		constexpr auto curPosition = 0x14;//íå íà àâòîäàìïå
		constexpr auto curVelocity = 0x20;//íå íà àâòîäàìïå
		constexpr auto travelTime = 0x2c;//íå íà àâòîäàìïå
		constexpr auto ShouldPool = 0x30;//íå íà àâòîäàìïå
		constexpr auto _disposed = 0x31;//íå íà àâòîäàìïå
	};
	namespace Projectile {
		constexpr auto moveDeltaTime = 0x0;
		constexpr auto lifeTime = 0x0;
		constexpr auto initialVelocity = 0x20;
		constexpr auto drag = 0x2C;
		constexpr auto gravityModifier = 0x30;
		constexpr auto thickness = 0x34;
		constexpr auto initialDistance = 0x38;
		constexpr auto remainInWorld = 0x3C;
		constexpr auto stickProbability = 0x40;
		constexpr auto breakProbability = 0x44;
		constexpr auto conditionLoss = 0x48;
		constexpr auto ricochetChance = 0x4C;
		constexpr auto penetrationPower = 0x50;
		constexpr auto waterIntegrityLoss = 0x54;
		constexpr auto damageProperties = 0x58;
		constexpr auto damageDistances = 0x60;
		constexpr auto damageMultipliers = 0x68;
		constexpr auto damageTypes = 0x70;
		constexpr auto rendererToScale = 0x78;
		constexpr auto firstPersonRenderer = 0x80;
		constexpr auto createDecals = 0x88;
		constexpr auto doDefaultHitEffects = 0x89;
		constexpr auto flybySound = 0x90;
		constexpr auto flybySoundDistance = 0x98;
		constexpr auto closeFlybySound = 0xA0;
		constexpr auto closeFlybyDistance = 0xA8;
		constexpr auto tumbleSpeed = 0xAC;
		constexpr auto tumbleAxis = 0xB0;
		constexpr auto swimScale = 0xBC;
		constexpr auto swimSpeed = 0xC8;
		constexpr auto owner = 0xD8;
		constexpr auto sourceWeaponPrefab = 0xE0;
		constexpr auto sourceProjectilePrefab = 0xE8;
		constexpr auto mod = 0xF0;
		constexpr auto projectileID = 0xF8;
		constexpr auto seed = 0xFC;
		constexpr auto clientsideEffect = 0x100;
		constexpr auto clientsideAttack = 0x101;
		constexpr auto integrity = 0x104;
		constexpr auto maxDistance = 0x108;
		constexpr auto modifier = 0x10C;
		constexpr auto invisible = 0x11C;
		constexpr auto noheadshots = 0x11D;
		constexpr auto currentVelocity = 0x120;
		constexpr auto currentPosition = 0x12C;
		constexpr auto traveledDistance = 0x138;
		constexpr auto traveledTime = 0x13C;
		constexpr auto launchTime = 0x140;
		constexpr auto sentPosition = 0x144;
		constexpr auto previousPosition = 0x150;
		constexpr auto previousVelocity = 0x15C;
		constexpr auto previousTraveledTime = 0x168;
		constexpr auto isUnderwater = 0x16C;
		constexpr auto isRicochet = 0x16D;
		constexpr auto isRetiring = 0x16E;
		constexpr auto flybyPlayed = 0x16F;
		constexpr auto wasFacingPlayer = 0x170;
		constexpr auto flybyPlane = 0x174;
		constexpr auto flybyRay = 0x184;
		constexpr auto cleanupAction = 0x1A0;
		constexpr auto hitTest = 0x1A8;
		constexpr auto swimRandom = 0x1B0;
		constexpr auto _fleshMaterialID = 0x0;
		constexpr auto _waterMaterialID = 0x4;
		constexpr auto cachedWaterString = 0x8;
	};
	namespace PlayerEyes {
		constexpr auto EyeOffset = 0x0;
		constexpr auto DuckOffset = 0xC;
		constexpr auto CrawlOffset = 0x18;
		constexpr auto ParachuteOffset = 0x24;
		constexpr auto thirdPersonSleepingOffset = 0x28;
		constexpr auto defaultLazyAim = 0x38;
		constexpr auto viewOffset = 0x40;
		constexpr auto bodyRotationk__BackingField = 0x4C;
		constexpr auto headAnglesk__BackingField = 0x5C;
		constexpr auto rotationLookk__BackingField = 0x68;
		constexpr auto postRotationLookk__BackingField = 0x78;
		constexpr auto postRotationLookAlphak__BackingField = 0x88;
		constexpr auto IsAltLookingLegsThresholdk__BackingField = 0x8C;
	};
	namespace ViewModel {
		constexpr auto viewModelPrefab = 0x20;
		constexpr auto targetEntity = 0x28;
		constexpr auto instance = 0x30;
	};
	namespace BowWeapon {
		constexpr auto attackReady = 0x3A8;
		constexpr auto arrowBack = 0x3AC;
		constexpr auto swapArrows = 0x3B0;
		constexpr auto wasAiming = 0x3B8;
	};
	namespace AttackEntity {
		constexpr auto deployDelay = 0x210;
		constexpr auto repeatDelay = 0x214;
		constexpr auto animationDelay = 0x218;
		constexpr auto effectiveRange = 0x21C;
		constexpr auto npcDamageScale = 0x220;
		constexpr auto attackLengthMin = 0x224;
		constexpr auto attackLengthMax = 0x228;
		constexpr auto attackSpacing = 0x22C;
		constexpr auto aiAimSwayOffset = 0x230;
		constexpr auto aiAimCone = 0x234;
		constexpr auto aiOnlyInRange = 0x238;
		constexpr auto CloseRangeAddition = 0x23C;
		constexpr auto MediumRangeAddition = 0x240;
		constexpr auto LongRangeAddition = 0x244;
		constexpr auto CanUseAtMediumRange = 0x248;
		constexpr auto CanUseAtLongRange = 0x249;
		constexpr auto reloadSounds = 0x250;
		constexpr auto thirdPersonMeleeSound = 0x258;
		constexpr auto recoilCompDelayOverride = 0x260;
		constexpr auto wantsRecoilComp = 0x264;
		constexpr auto showCrosshairOnTutorial = 0x265;
		constexpr auto noHeadshots = 0x266;
		constexpr auto nextAttackTime = 0x268;
		constexpr auto lastTickTime = 0x26C;
		constexpr auto nextTickTime = 0x270;
		constexpr auto timeSinceDeploy = 0x274;
		constexpr auto reductionSpeedScalars = 0x0;
		constexpr auto lastRecoilCompTime = 0x278;
		constexpr auto startAimingDirection = 0x27C;
		constexpr auto wasDoingRecoilComp = 0x288;
		constexpr auto reductionSpeed = 0x28C;
	};
	namespace BaseEntity {
		constexpr auto ragdoll = 0x80;
		constexpr auto positionLerp = 0x88;
		constexpr auto menuOptions = 0x90;
		constexpr auto bounds = 0x98;
		constexpr auto impactEffect = 0xB0;
		constexpr auto enableSaving = 0xB8;
		constexpr auto syncPosition = 0xB9;
		constexpr auto model = 0xC0;
		constexpr auto flags = 0xC8;
		constexpr auto parentBone = 0xCC;
		constexpr auto skinID = 0xD0;
		constexpr auto _components = 0xD8;
		constexpr auto HasBrain = 0xE0;
		constexpr auto _name = 0xE8;
		constexpr auto OwnerIDk__BackingField = 0xF0;
		constexpr auto globalBroadcastQueue = 0x0;
		constexpr auto globalBroadcastProtocol = 0x8;
		constexpr auto broadcastProtocol = 0xF8;
		constexpr auto links = 0x100;
		constexpr auto linkedToNeighbours = 0x108;
		constexpr auto MaxFileRequestsPerSecond = 0x0;
		constexpr auto QueuedFileRequests = 0x10;
		constexpr auto _fileRequestCounter = 0x18;
		constexpr auto _flushQueuedFileRequests = 0x30;
		constexpr auto _pendingFileRequests = 0x110;
		constexpr auto updateParentingAction = 0x118;
		constexpr auto addedToParentEntity = 0x120;
		constexpr auto RpcClientDeprecationNotice = 0x0;
		constexpr auto itemSkin = 0x128;
		constexpr auto successCallback = 0x130;
		constexpr auto failureCallback = 0x138;
		constexpr auto entitySlots = 0x140;
		constexpr auto triggers = 0x148;
		constexpr auto isVisible = 0x150;
		constexpr auto isAnimatorVisible = 0x151;
		constexpr auto isShadowVisible = 0x152;
		constexpr auto localOccludee = 0x158;
		constexpr auto Weightk__BackingField = 0x178;
	};
	namespace UnityEngine_Physics {
		constexpr auto ContactModifyEventCCD = 0x8;//íå íà àâòîäàìïå
	};
	namespace AssetNameCache {
		constexpr auto lower = 0x8;//íå íà àâòîäàìïå
		constexpr auto upper = 0x10;//íå íà àâòîäàìïå
	};
	namespace HitTest {
		constexpr auto type = 0x10;
		constexpr auto AttackRay = 0x14;
		constexpr auto Radius = 0x2C;
		constexpr auto Forgiveness = 0x30;
		constexpr auto MaxDistance = 0x34;
		constexpr auto RayHit = 0x38;
		constexpr auto MultiHit = 0x64;
		constexpr auto BestHit = 0x65;
		constexpr auto DidHit = 0x66;
		constexpr auto damageProperties = 0x68;
		constexpr auto gameObject = 0x70;
		constexpr auto collider = 0x78;
		constexpr auto ignoreEntity = 0x80;
		constexpr auto ignoredType = 0x88;
		constexpr auto HitEntity = 0x90;
		constexpr auto HitPoint = 0x98;
		constexpr auto HitNormal = 0xA4;
		constexpr auto HitDistance = 0xB0;
		constexpr auto HitTransform = 0xB8;
		constexpr auto HitPart = 0xC0;
		constexpr auto HitMaterial = 0xC8;
	};
	namespace UnityEngine_Quaternion {
		constexpr auto x = 0x10;//íå íà àâòîäàìïå
		constexpr auto y = 0x14;//íå íà àâòîäàìïå
		constexpr auto z = 0x18;//íå íà àâòîäàìïå
		constexpr auto w = 0x1c;//íå íà àâòîäàìïå
	};
	namespace GamePhysics {
		constexpr auto BufferLength = 0x0;
		constexpr auto hitBuffer = 0x0;
		constexpr auto hitBufferB = 0x8;
		constexpr auto colBuffer = 0x10;
	};
	namespace System_Math {
		constexpr auto roundPower10Double = 0x8;//íå íà àâòîäàìïå
	};
	namespace Door {
		constexpr auto __menuOption_Menu_CloseDoor = 0x2D8;
		constexpr auto __menuOption_Menu_KnockDoor = 0x348;
		constexpr auto __menuOption_Menu_OpenDoor = 0x3B8;
		constexpr auto __menuOption_Menu_ToggleHatch = 0x428;
		constexpr auto knockEffect = 0x498;
		constexpr auto canTakeLock = 0x4A0;
		constexpr auto hasHatch = 0x4A1;
		constexpr auto canTakeCloser = 0x4A2;
		constexpr auto canTakeKnocker = 0x4A3;
		constexpr auto canNpcOpen = 0x4A4;
		constexpr auto canHandOpen = 0x4A5;
		constexpr auto isSecurityDoor = 0x4A6;
		constexpr auto canReverseOpen = 0x4A7;
		constexpr auto vehiclePhysBoxes = 0x4A8;
		constexpr auto checkPhysBoxesOnOpen = 0x4B0;
		constexpr auto vehicleCollisionSfx = 0x4B8;
		constexpr auto ClosedColliderRoots = 0x4C0;
		constexpr auto allowOnCargoShip = 0x4C8;
		constexpr auto openAnimLength = 0x4CC;
		constexpr auto closeAnimLength = 0x4D0;
		constexpr auto ReverseOpen = 0x0;
		constexpr auto NavMeshVolumeAnimals = 0x4D8;
		constexpr auto NavMeshVolumeHumanoids = 0x4E0;
		constexpr auto NpcTriggerBox = 0x4E8;
		constexpr auto NavMeshLink = 0x4F0;
		constexpr auto openHash = 0x0;
		constexpr auto closeHash = 0x4;
		constexpr auto reverseOpenHash = 0x8;
	};
	namespace UnityEngine_Object {
		constexpr auto m_CachedPtr = 0x10;//íå íà àâòîäàìïå
	};
	namespace BaseMelee {
		constexpr auto damageProperties = 0x298;
		constexpr auto damageTypes = 0x2A0;
		constexpr auto maxDistance = 0x2A8;
		constexpr auto attackRadius = 0x2AC;
		constexpr auto isAutomatic = 0x2B0;
		constexpr auto blockSprintOnAttack = 0x2B1;
		constexpr auto canUntieCrates = 0x2B2;
		constexpr auto longResourceForgiveness = 0x2B3;
		constexpr auto strikeFX = 0x2B8;
		constexpr auto useStandardHitEffects = 0x2C0;
		constexpr auto aiStrikeDelay = 0x2C4;
		constexpr auto swingEffect = 0x2C8;
		constexpr auto materialStrikeFX = 0x2D0;
		constexpr auto heartStress = 0x2D8;
		constexpr auto gathering = 0x2E0;
		constexpr auto throwReady = 0x2E8;
		constexpr auto canThrowAsProjectile = 0x2E9;
		constexpr auto canAiHearIt = 0x2EA;
		constexpr auto onlyThrowAsProjectile = 0x2EB;
	};
	namespace ItemModProjectile {
		constexpr auto projectileObject = 0x20;
		constexpr auto mods = 0x28;
		constexpr auto ammoType = 0x30;
		constexpr auto numProjectiles = 0x34;
		constexpr auto projectileSpread = 0x38;
		constexpr auto projectileVelocity = 0x3C;
		constexpr auto projectileVelocitySpread = 0x40;
		constexpr auto useCurve = 0x44;
		constexpr auto spreadScalar = 0x48;
		constexpr auto attackEffectOverride = 0x50;
		constexpr auto barrelConditionLoss = 0x58;
		constexpr auto category = 0x60;
	};
	namespace RecoilProperties {
		constexpr auto recoilYawMin = 0x18;
		constexpr auto recoilYawMax = 0x1C;
		constexpr auto recoilPitchMin = 0x20;
		constexpr auto recoilPitchMax = 0x24;
		constexpr auto timeToTakeMin = 0x28;
		constexpr auto timeToTakeMax = 0x2C;
		constexpr auto ADSScale = 0x30;
		constexpr auto movementPenalty = 0x34;
		constexpr auto clampPitch = 0x38;
		constexpr auto pitchCurve = 0x40;
		constexpr auto yawCurve = 0x48;
		constexpr auto useCurves = 0x50;
		constexpr auto curvesAsScalar = 0x51;
		constexpr auto shotsUntilMax = 0x54;
		constexpr auto maxRecoilRadius = 0x58;
		constexpr auto overrideAimconeWithCurve = 0x5C;
		constexpr auto aimconeCurveScale = 0x60;
		constexpr auto aimconeCurve = 0x68;
		constexpr auto aimconeProbabilityCurve = 0x70;
		constexpr auto ammoAimconeScaleMultiProjectile = 0x78;
		constexpr auto ammoAimconeScaleSingleProjectile = 0x7C;
		constexpr auto newRecoilOverride = 0x80;
	};
	namespace ItemDefinition {
		constexpr auto itemid = 0x20;
		constexpr auto shortname = 0x28;
		constexpr auto displayName = 0x30;
		constexpr auto displayDescription = 0x38;
		constexpr auto iconSprite = 0x40;
		constexpr auto category = 0x48;
		constexpr auto selectionPanel = 0x4C;
		constexpr auto maxDraggable = 0x50;
		constexpr auto itemType = 0x54;
		constexpr auto amountType = 0x58;
		constexpr auto occupySlots = 0x5C;
		constexpr auto stackable = 0x60;
		constexpr auto volume = 0x64;
		constexpr auto quickDespawn = 0x68;
		constexpr auto blockStealingInSafeZone = 0x69;
		constexpr auto tutorialAllowance = 0x6C;
		constexpr auto rarity = 0x70;
		constexpr auto despawnRarity = 0x74;
		constexpr auto spawnAsBlueprint = 0x78;
		constexpr auto inventoryGrabSound = 0x80;
		constexpr auto inventoryDropSound = 0x88;
		constexpr auto physImpactSoundDef = 0x90;
		constexpr auto condition = 0x98;
		constexpr auto hidden = 0xB0;
		constexpr auto flags = 0xB4;
		constexpr auto hideSelectedPanel = 0xB8;
		constexpr auto steamItem = 0xC0;
		constexpr auto steamDlc = 0xC8;
		constexpr auto Parent = 0xD0;
		constexpr auto worldModelPrefab = 0xD8;
		constexpr auto worldModelOverrides = 0xE0;
		constexpr auto treatAsComponentForRepairs = 0xE8;
		constexpr auto AlignWorldModelOnDrop = 0xE9;
		constexpr auto WorldModelDropOffset = 0xEC;
		constexpr auto isRedirectOf = 0xF8;
		constexpr auto redirectVendingBehaviour = 0x100;
		constexpr auto itemMods = 0x108;
		constexpr auto Traits = 0x110;
		constexpr auto skins = 0x118;
		constexpr auto _skins2 = 0x120;
		constexpr auto panel = 0x128;
		constexpr auto ItemModWearablek__BackingField = 0x130;
		constexpr auto ItemModBurnablek__BackingField = 0x138;
		constexpr auto ItemModCookablek__BackingField = 0x140;
		constexpr auto isHoldablek__BackingField = 0x148;
		constexpr auto isUsablek__BackingField = 0x149;
		constexpr auto CraftableWithSkink__BackingField = 0x14A;
		constexpr auto Children = 0x150;
	};
	namespace PlayerInput {
		constexpr auto state = 0x28;
		constexpr auto hadInputBuffer = 0x30;
		constexpr auto bodyRotation = 0x34;
		constexpr auto bodyAngles = 0x44;
		constexpr auto bodyAnglesOverride = 0x50;
		constexpr auto clearBodyAnglesOverrideOnLerpComplete = 0x5C;
		constexpr auto bodyAnglesOverrideLerpSpeed = 0x60;
		constexpr auto headRotation = 0x64;
		constexpr auto headAngles = 0x74;
		constexpr auto recoilAngles = 0x80;
		constexpr auto viewDelta = 0x8C;
		constexpr auto headLerp = 0x94;
		constexpr auto mouseWheelUp = 0x98;
		constexpr auto mouseWheelDn = 0x9C;
		constexpr auto autorun = 0xA0;
		constexpr auto toggleDuck = 0xA1;
		constexpr auto toggleAds = 0xA2;
		constexpr auto lastAdsEntity = 0xA8;
		constexpr auto pendingMouseDelta = 0xB0;
		constexpr auto offsetAngles = 0xBC;
		constexpr auto ignoredButtons = 0xC8;
		constexpr auto hasKeyFocus = 0xCC;
	};
	namespace PlayerModel {
		constexpr auto speed = 0x0;
		constexpr auto acceleration = 0x4;
		constexpr auto rotationYaw = 0x8;
		constexpr auto forward = 0xC;
		constexpr auto right = 0x10;
		constexpr auto up = 0x14;
		constexpr auto ducked = 0x18;
		constexpr auto grounded = 0x1C;
		constexpr auto crawling = 0x20;
		constexpr auto waterlevel = 0x24;
		constexpr auto attack = 0x28;
		constexpr auto attack_alt = 0x2C;
		constexpr auto deploy = 0x30;
		constexpr auto turnOn = 0x34;
		constexpr auto turnOff = 0x38;
		constexpr auto reload = 0x3C;
		constexpr auto throwWeapon = 0x40;
		constexpr auto holster = 0x44;
		constexpr auto aiming = 0x48;
		constexpr auto onLadder = 0x4C;
		constexpr auto posing = 0x50;
		constexpr auto poseType = 0x54;
		constexpr auto relaxGunPose = 0x58;
		constexpr auto vehicle_aim_yaw = 0x5C;
		constexpr auto vehicle_aim_speed = 0x60;
		constexpr auto usePoseTransition = 0x64;
		constexpr auto onPhone = 0x68;
		constexpr auto leftFootIK = 0x6C;
		constexpr auto rightFootIK = 0x70;
		constexpr auto vehicleSteering = 0x74;
		constexpr auto sitReaction = 0x78;
		constexpr auto forwardReaction = 0x7C;
		constexpr auto rightReaction = 0x80;
		constexpr auto ladderType = 0x84;
		constexpr auto hasParachute = 0x88;
		constexpr auto nonGroundedTime = 0x8C;
		constexpr auto deployParachuteTrigger = 0x90;
		constexpr auto collision = 0x20;
		constexpr auto censorshipCube = 0x28;
		constexpr auto censorshipCubeBreasts = 0x30;
		constexpr auto jawBone = 0x38;
		constexpr auto neckBone = 0x40;
		constexpr auto headBone = 0x48;
		constexpr auto eyeController = 0x50;
		constexpr auto blinkController = 0x58;
		constexpr auto SpineBones = 0x60;
		constexpr auto leftFootBone = 0x68;
		constexpr auto rightFootBone = 0x70;
		constexpr auto leftHandPropBone = 0x78;
		constexpr auto rightHandPropBone = 0x80;
		constexpr auto rightHandTarget = 0x88;
		constexpr auto isPreview = 0x94;
		constexpr auto leftHandTargetPosition = 0x98;
		constexpr auto leftHandTargetRotation = 0xA4;
		constexpr auto rightHandTargetPosition = 0xB4;
		constexpr auto rightHandTargetRotation = 0xC0;
		constexpr auto steeringTargetDegrees = 0xD0;
		constexpr auto rightFootTargetPosition = 0xD4;
		constexpr auto rightFootTargetRotation = 0xE0;
		constexpr auto leftFootTargetPosition = 0xF0;
		constexpr auto leftFootTargetRotation = 0xFC;
		constexpr auto CinematicAnimationController = 0x110;
		constexpr auto DefaultAvatar = 0x118;
		constexpr auto CinematicAvatar = 0x120;
		constexpr auto DefaultHoldType = 0x128;
		constexpr auto SleepGesture = 0x130;
		constexpr auto CrawlToIncapacitatedGesture = 0x138;
		constexpr auto StandToIncapacitatedGesture = 0x140;
		constexpr auto CurrentGesture = 0x148;
		constexpr auto MaleSkin = 0x150;
		constexpr auto FemaleSkin = 0x158;
		constexpr auto subsurfaceProfile = 0x160;
		constexpr auto voiceVolume = 0x168;
		constexpr auto skinColor = 0x16C;
		constexpr auto skinNumber = 0x170;
		constexpr auto meshNumber = 0x174;
		constexpr auto hairNumber = 0x178;
		constexpr auto skinType = 0x17C;
		constexpr auto movementSounds = 0x180;
		constexpr auto showSash = 0x188;
		constexpr auto tempPoseType = 0x18C;
		constexpr auto underwearSkin = 0x190;
		constexpr auto overrideSkinSeedk__BackingField = 0x198;
		constexpr auto AimAnglesk__BackingField = 0x1A0;
		constexpr auto LookAnglesk__BackingField = 0x1B0;
		constexpr auto LayerHands = 0x0;
		constexpr auto LayerGestures = 0x0;
		constexpr auto LayerPlayerGesturesUpperBody = 0x0;
		constexpr auto LayerPlayerGesturesFullBody = 0x0;
		constexpr auto LayerReactions = 0x0;
		constexpr auto modelState = 0x1C0;
		constexpr auto position = 0x1C8;
		constexpr auto velocity = 0x1D4;
		constexpr auto speedOverride = 0x1E0;
		constexpr auto newVelocity = 0x1EC;
		constexpr auto rotation = 0x1F8;
		constexpr auto mountedRotation = 0x208;
		constexpr auto fallingTime = 0x218;
		constexpr auto smoothLeftFootIK = 0x21C;
		constexpr auto smoothRightFootIK = 0x228;
		constexpr auto drawShadowOnly = 0x234;
		constexpr auto isIncapacitated = 0x235;
		constexpr auto flinchLocation = 0x238;
		constexpr auto visible = 0x23C;
		constexpr auto nameTag = 0x240;
		constexpr auto animatorNeedsWarmup = 0x248;
		constexpr auto isLocalPlayer = 0x249;
		constexpr auto aimSoundDef = 0x250;
		constexpr auto aimEndSoundDef = 0x258;
		constexpr auto InGesture = 0x260;
		constexpr auto CurrentGestureConfig = 0x268;
		constexpr auto InCinematic = 0x270;
		constexpr auto defaultAnimatorController = 0x278;
		constexpr auto _multiMesh = 0x280;
		constexpr auto _animator = 0x288;
		constexpr auto _lodGroup = 0x290;
		constexpr auto _currentGesture = 0x298;
		constexpr auto holdTypeLock = 0x2A0;
		constexpr auto hasHeldEntity = 0x2A4;
		constexpr auto wasMountedRightAim = 0x2A5;
		constexpr auto cachedMask = 0x2A8;
		constexpr auto cachedConstructionMask = 0x2AC;
		constexpr auto WorkshopHeldEntity = 0x2B0;
		constexpr auto wasCrawling = 0x2B8;
		constexpr auto mountedSpineLookWeight = 0x2BC;
		constexpr auto mountedAnimSpeed = 0x2C0;
		constexpr auto preserveBones = 0x2C4;
		constexpr auto downLimitOverride = 0x2C8;
		constexpr auto blendShapeControllers = 0x2D0;
		constexpr auto IsNpck__BackingField = 0x2D8;
		constexpr auto timeSinceReactionStart = 0x2DC;
		constexpr auto timeSinceLeftFootTest = 0x2E0;
		constexpr auto cachedLeftFootPos = 0x2E4;
		constexpr auto cachedLeftFootNormal = 0x2F0;
		constexpr auto timeSinceRightFootTest = 0x2FC;
		constexpr auto cachedRightFootPos = 0x300;
		constexpr auto cachedRightFootNormal = 0x30C;
		constexpr auto pm_uplimit = 0x94;
		constexpr auto pm_downlimit = 0x98;
		constexpr auto pm_upspine = 0x9C;
		constexpr auto pm_downspine = 0xA0;
		constexpr auto pm_lookoffset = 0xA4;
		constexpr auto pm_anglesmoothspeed = 0xB0;
		constexpr auto pm_nohold = 0xB4;
		constexpr auto pm_ladder = 0xB8;
		constexpr auto pm_minweight = 0xBC;
		constexpr auto _smoothAimWeight = 0x318;
		constexpr auto _smoothVelocity = 0x31C;
		constexpr auto _smoothlookAngle = 0x320;
		constexpr auto allowMountedHeadLook = 0x32C;
		constexpr auto overrideLeftHandIkWeight = 0x330;
		constexpr auto overrideRightHandIkWeight = 0x334;
		constexpr auto smoothLookDir = 0x338;
		constexpr auto lastSafeLookDir = 0x344;
		constexpr auto cinematicLookAt = 0x350;
		constexpr auto lastCinematicLookAt = 0x35C;
		constexpr auto cinematicLookAtWeight = 0x368;
		constexpr auto cinematicTargetWeight = 0x36C;
		constexpr auto Shoulders = 0x370;
		constexpr auto AdditionalSpineBones = 0x378;
		constexpr auto FinishedLegWearables = 0xC0;
		constexpr auto LegParts = 0x380;
		constexpr auto fadeToggles = 0x388;
		constexpr auto fakeSpineBones = 0x390;
		constexpr auto extraLeanBack = 0x398;
		constexpr auto drawState = 0x39C;
		constexpr auto timeInArmsMode = 0x3A0;
	};
	namespace ProtoBuf_PlayerTeam {
		constexpr auto teamID = 0x10;//íå íà àâòîäàìïå
		constexpr auto teamName = 0x18;//íå íà àâòîäàìïå
		constexpr auto teamLeader = 0x20;//íå íà àâòîäàìïå
		constexpr auto members = 0x28;//íå íà àâòîäàìïå
		constexpr auto teamLifetime = 0x30;//íå íà àâòîäàìïå
		constexpr auto mapNote = 0x38;//íå íà àâòîäàìïå
		constexpr auto ShouldPool = 0x40;//íå íà àâòîäàìïå
		constexpr auto _disposed = 0x41;//íå íà àâòîäàìïå
	};
	namespace PlayerInventory {
		constexpr auto containerMain = 0x28;
		constexpr auto containerBelt = 0x30;
		constexpr auto containerWear = 0x38;
		constexpr auto crafting = 0x40;
		constexpr auto loot = 0x48;
		constexpr auto BackpackGroundedError = 0x0;
		constexpr auto lastSet = 0x50;
		constexpr auto cachedResult = 0x58;
		constexpr auto returnItems = 0x68;
	};
	namespace ItemContainer {
		constexpr auto BackpackSlotIndex = 0x0;
		constexpr auto flags = 0x10;
		constexpr auto allowedContents = 0x14;
		constexpr auto onlyAllowedItems = 0x18;
		constexpr auto availableSlots = 0x20;
		constexpr auto capacity = 0x28;
		constexpr auto uid = 0x30;
		constexpr auto dirty = 0x38;
		constexpr auto itemList = 0x40;
		constexpr auto temperature = 0x48;
		constexpr auto parent = 0x50;
		constexpr auto playerOwner = 0x58;
		constexpr auto entityOwner = 0x60;
		constexpr auto isServer = 0x68;
		constexpr auto maxStackSize = 0x6C;
		constexpr auto containerVolume = 0x70;
	};
	namespace Item {
		constexpr auto DefaultArmourBreakEffectPath = 0x0;
		constexpr auto _condition = 0x10;
		constexpr auto _maxCondition = 0x14;
		constexpr auto info = 0x18;
		constexpr auto uid = 0x20;
		constexpr auto dirty = 0x28;
		constexpr auto amount = 0x2C;
		constexpr auto position = 0x30;
		constexpr auto busyTime = 0x34;
		constexpr auto removeTime = 0x38;
		constexpr auto fuel = 0x3C;
		constexpr auto isServer = 0x40;
		constexpr auto instanceData = 0x48;
		constexpr auto skin = 0x50;
		constexpr auto name = 0x58;
		constexpr auto streamerName = 0x60;
		constexpr auto text = 0x68;
		constexpr auto ammoCountk__BackingField = 0x70;
		constexpr auto cookTimeLeft = 0x78;
		constexpr auto progressBar = 0x7C;
		constexpr auto OnDirty = 0x80;
		constexpr auto flags = 0x88;
		constexpr auto contents = 0x90;
		constexpr auto parent = 0x98;
		constexpr auto worldEnt = 0xA0;
		constexpr auto heldEntity = 0xB0;
		constexpr auto amountOverride = 0xC0;
		constexpr auto FormatAmountMemoized = 0x0;
	};
	namespace Model {
		constexpr auto collision = 0x20;
		constexpr auto rootBone = 0x28;
		constexpr auto headBone = 0x30;
		constexpr auto eyeBone = 0x38;
		constexpr auto animator = 0x40;
		constexpr auto skeleton = 0x48;
		constexpr auto boneTransforms = 0x50;
		constexpr auto boneNames = 0x58;
		constexpr auto boneDict = 0x60;
		constexpr auto skin = 0x68;
		constexpr auto _lodGroup = 0x70;
	};
	namespace MedicalTool {
		constexpr auto healDurationSelf = 0x298;
		constexpr auto healDurationOther = 0x29C;
		constexpr auto healDurationOtherWounded = 0x2A0;
		constexpr auto maxDistanceOther = 0x2A4;
		constexpr auto canUseOnOther = 0x2A8;
		constexpr auto canRevive = 0x2A9;
		constexpr auto useTarget = 0x2B0;
		constexpr auto resetTime = 0x2B8;
	};
	namespace HeldEntity {
		constexpr auto worldModelAnimator = 0x180;
		constexpr auto thirdPersonDeploySound = 0x188;
		constexpr auto thirdPersonAimSound = 0x190;
		constexpr auto thirdPersonAimEndSound = 0x198;
		constexpr auto viewModelk__BackingField = 0x1A0;
		constexpr auto isDeployed = 0x1A8;
		constexpr auto Spine4BoneId = 0x0;
		constexpr auto Spine3BoneId = 0x4;
		constexpr auto lastExamineTime = 0x8;
		constexpr auto nextExamineTime = 0x1AC;
		constexpr auto Flag_ForceVisible = 0x0;
		constexpr auto handBone = 0x1B0;
		constexpr auto HoldAnimationOverride = 0x1B8;
		constexpr auto isBuildingTool = 0x1C0;
		constexpr auto hostileScore = 0x1C4;
		constexpr auto holsterInfo = 0x1C8;
		constexpr auto HeldCameraMode = 0x1D0;
		constexpr auto FirstPersonArmOffset = 0x1D4;
		constexpr auto FirstPersonArmRotation = 0x1E0;
		constexpr auto FirstPersonRotationStrength = 0x1EC;
		constexpr auto ownerItemUID = 0x1F0;
		constexpr auto _punches = 0x1F8;
		constexpr auto punchAdded = 0x200;
		constexpr auto lastPunchTime = 0x20C;
	};
	namespace UnityEngine_GUIContent {
		constexpr auto m_Text = 0x10;//íå íà àâòîäàìïå
		constexpr auto m_Image = 0x18;//íå íà àâòîäàìïå
		constexpr auto m_Tooltip = 0x20;//íå íà àâòîäàìïå
		constexpr auto s_Image = 0x8;//íå íà àâòîäàìïå
		constexpr auto s_TextImage = 0x10;//íå íà àâòîäàìïå
		constexpr auto none = 0x18;//íå íà àâòîäàìïå
	};
	namespace BaseCombatEntity {
		constexpr auto __menuOption_Menu_Pickup = 0x180;
		constexpr auto skeletonProperties = 0x1F0;
		constexpr auto baseProtection = 0x1F8;
		constexpr auto startHealth = 0x200;
		constexpr auto pickup = 0x208;
		constexpr auto repair = 0x230;
		constexpr auto ShowHealthInfo = 0x260;
		constexpr auto lifestate = 0x264;
		constexpr auto sendsHitNotification = 0x268;
		constexpr auto sendsMeleeHitNotification = 0x269;
		constexpr auto markAttackerHostile = 0x26A;
		constexpr auto _health = 0x26C;
		constexpr auto _maxHealth = 0x270;
		constexpr auto faction = 0x274;
		constexpr auto deathTime = 0x278;
		constexpr auto lastNotifyFrame = 0x27C;
	};
	namespace InputState {
		constexpr auto current = 0x10;
		constexpr auto previous = 0x18;
		constexpr auto SwallowedButtons = 0x20;
	};
	namespace InputMessage {
		constexpr auto buttons = 0x10;//íå íà àâòîäàìïå
		constexpr auto aimAngles = 0x14;//íå íà àâòîäàìïå
		constexpr auto mouseDelta = 0x20;//íå íà àâòîäàìïå
		constexpr auto ShouldPool = 0x2c;//íå íà àâòîäàìïå
		constexpr auto _disposed = 0x2d;//íå íà àâòîäàìïå
	};
	namespace BaseMountable {
		constexpr auto __menuOption_Menu_ClothingBlocked = 0x280;
		constexpr auto __menuOption_Menu_Mount = 0x2F0;
		constexpr auto dismountPhrase = 0x0;
		constexpr auto eyePositionOverride = 0x360;
		constexpr auto eyeCenterOverride = 0x368;
		constexpr auto pitchClamp = 0x370;
		constexpr auto yawClamp = 0x378;
		constexpr auto canWieldItems = 0x380;
		constexpr auto relativeViewAngles = 0x381;
		constexpr auto mountAnchor = 0x388;
		constexpr auto mountLOSVertOffset = 0x390;
		constexpr auto mountPose = 0x394;
		constexpr auto maxMountDistance = 0x398;
		constexpr auto dismountPositions = 0x3A0;
		constexpr auto checkPlayerLosOnMount = 0x3A8;
		constexpr auto disableMeshCullingForPlayers = 0x3A9;
		constexpr auto allowHeadLook = 0x3AA;
		constexpr auto ignoreVehicleParent = 0x3AB;
		constexpr auto legacyDismount = 0x3AC;
		constexpr auto wearWhileMounted = 0x3B0;
		constexpr auto modifiesPlayerCollider = 0x3B8;
		constexpr auto customPlayerCollider = 0x3BC;
		constexpr auto clippingAndVisChecks = 0x3D0;
		constexpr auto clippingChecksLocation = 0x3D4;
		constexpr auto mountSoundDef = 0x3D8;
		constexpr auto swapSoundDef = 0x3E0;
		constexpr auto dismountSoundDef = 0x3E8;
		constexpr auto dismountHoldType = 0x3F0;
		constexpr auto mountTimeStatType = 0x3F4;
		constexpr auto allowedGestures = 0x3F8;
		constexpr auto canDrinkWhileMounted = 0x3FC;
		constexpr auto allowSleeperMounting = 0x3FD;
		constexpr auto animateClothInLocalSpace = 0x3FE;
		constexpr auto MountedCameraMode = 0x400;
		constexpr auto rigidBody = 0x408;
		constexpr auto isMobile = 0x410;
		constexpr auto SideLeanAmount = 0x414;
		constexpr auto playerHeight = 0x0;
		constexpr auto playerRadius = 0x0;
	};
	namespace TOD_Sky {
		constexpr auto ColorSpace = 0x18;//íå íà àâòîäàìïå
		constexpr auto ColorRange = 0x1c;//íå íà àâòîäàìïå
		constexpr auto ColorOutput = 0x20;//íå íà àâòîäàìïå
		constexpr auto SkyQuality = 0x24;//íå íà àâòîäàìïå
		constexpr auto CloudQuality = 0x28;//íå íà àâòîäàìïå
		constexpr auto MeshQuality = 0x2c;//íå íà àâòîäàìïå
		constexpr auto StarQuality = 0x30;//íå íà àâòîäàìïå
		constexpr auto Cycle = 0x38;//íå íà àâòîäàìïå
		constexpr auto World = 0x40;//íå íà àâòîäàìïå
		constexpr auto Atmosphere = 0x48;//íå íà àâòîäàìïå
		constexpr auto Day = 0x50;//íå íà àâòîäàìïå
		constexpr auto Night = 0x58;//íå íà àâòîäàìïå
		constexpr auto Sun = 0x60;//íå íà àâòîäàìïå
		constexpr auto Moon = 0x68;//íå íà àâòîäàìïå
		constexpr auto Stars = 0x70;//íå íà àâòîäàìïå
		constexpr auto Clouds = 0x78;//íå íà àâòîäàìïå
		constexpr auto Light = 0x80;//íå íà àâòîäàìïå
		constexpr auto Fog = 0x88;//íå íà àâòîäàìïå
		constexpr auto Ambient = 0x90;//íå íà àâòîäàìïå
		constexpr auto Reflection = 0x98;//íå íà àâòîäàìïå
		constexpr auto Initializedk__BackingField = 0xa0;//íå íà àâòîäàìïå
		constexpr auto Componentsk__BackingField = 0xa8;//íå íà àâòîäàìïå
		constexpr auto Resourcesk__BackingField = 0xb0;//íå íà àâòîäàìïå
		constexpr auto IsDayk__BackingField = 0xb8;//íå íà àâòîäàìïå
		constexpr auto IsNightk__BackingField = 0xb9;//íå íà àâòîäàìïå
		constexpr auto LerpValuek__BackingField = 0xbc;//íå íà àâòîäàìïå
		constexpr auto SunZenithk__BackingField = 0xc0;//íå íà àâòîäàìïå
		constexpr auto SunAltitudek__BackingField = 0xc4;//íå íà àâòîäàìïå
		constexpr auto SunAzimuthk__BackingField = 0xc8;//íå íà àâòîäàìïå
		constexpr auto MoonZenithk__BackingField = 0xcc;//íå íà àâòîäàìïå
		constexpr auto MoonAltitudek__BackingField = 0xd0;//íå íà àâòîäàìïå
		constexpr auto MoonAzimuthk__BackingField = 0xd4;//íå íà àâòîäàìïå
		constexpr auto SunsetTimek__BackingField = 0xd8;//íå íà àâòîäàìïå
		constexpr auto SunriseTimek__BackingField = 0xdc;//íå íà àâòîäàìïå
		constexpr auto LocalSiderealTimek__BackingField = 0xe0;//íå íà àâòîäàìïå
		constexpr auto SunVisibilityk__BackingField = 0xe4;//íå íà àâòîäàìïå
		constexpr auto MoonVisibilityk__BackingField = 0xe8;//íå íà àâòîäàìïå
		constexpr auto SunDirectionk__BackingField = 0xec;//íå íà àâòîäàìïå
		constexpr auto MoonDirectionk__BackingField = 0xf8;//íå íà àâòîäàìïå
		constexpr auto LightDirectionk__BackingField = 0x104;//íå íà àâòîäàìïå
		constexpr auto LocalSunDirectionk__BackingField = 0x110;//íå íà àâòîäàìïå
		constexpr auto LocalMoonDirectionk__BackingField = 0x11c;//íå íà àâòîäàìïå
		constexpr auto LocalLightDirectionk__BackingField = 0x128;//íå íà àâòîäàìïå
		constexpr auto SunLightColork__BackingField = 0x134;//íå íà àâòîäàìïå
		constexpr auto MoonLightColork__BackingField = 0x144;//íå íà àâòîäàìïå
		constexpr auto SunRayColork__BackingField = 0x154;//íå íà àâòîäàìïå
		constexpr auto MoonRayColork__BackingField = 0x164;//íå íà àâòîäàìïå
		constexpr auto SunSkyColork__BackingField = 0x174;//íå íà àâòîäàìïå
		constexpr auto MoonSkyColork__BackingField = 0x184;//íå íà àâòîäàìïå
		constexpr auto SunMeshColork__BackingField = 0x194;//íå íà àâòîäàìïå
		constexpr auto MoonMeshColork__BackingField = 0x1a4;//íå íà àâòîäàìïå
		constexpr auto SunCloudColork__BackingField = 0x1b4;//íå íà àâòîäàìïå
		constexpr auto MoonCloudColork__BackingField = 0x1c4;//íå íà àâòîäàìïå
		constexpr auto FogColork__BackingField = 0x1d4;//íå íà àâòîäàìïå
		constexpr auto GroundColork__BackingField = 0x1e4;//íå íà àâòîäàìïå
		constexpr auto AmbientColork__BackingField = 0x1f4;//íå íà àâòîäàìïå
		constexpr auto MoonHaloColork__BackingField = 0x204;//íå íà àâòîäàìïå
		constexpr auto ReflectionCur = 0x218;//íå íà àâòîäàìïå
		constexpr auto ReflectionSrc = 0x220;//íå íà àâòîäàìïå
		constexpr auto ReflectionDst = 0x228;//íå íà àâòîäàìïå
		constexpr auto ReflectionUpdateSpeed = 0x8;//íå íà àâòîäàìïå
		constexpr auto ReflectionResolution = 0xc;//íå íà àâòîäàìïå
		constexpr auto ReflectionUpdateInterval = 0x10;//íå íà àâòîäàìïå
		constexpr auto ReflectionTimeSlicing = 0x14;//íå íà àâòîäàìïå
		constexpr auto timeSinceLightUpdate = 0x230;//íå íà àâòîäàìïå
		constexpr auto timeSinceAmbientUpdate = 0x234;//íå íà àâòîäàìïå
		constexpr auto timeSinceReflectionUpdate = 0x238;//íå íà àâòîäàìïå
		constexpr auto kBetaMie = 0x23c;//íå íà àâòîäàìïå
		constexpr auto kSun = 0x248;//íå íà àâòîäàìïå
		constexpr auto k4PI = 0x258;//íå íà àâòîäàìïå
		constexpr auto kRadius = 0x268;//íå íà àâòîäàìïå
		constexpr auto kScale = 0x278;//íå íà àâòîäàìïå
	};
	namespace UnityEngine_PhysicsScene {
		constexpr auto m_Handle = 0x10;//íå íà àâòîäàìïå
	};
	namespace BaseHelicopter {
		constexpr auto __menuOption_Menu_Push = 0x4C0;
		constexpr auto engineThrustMax = 0x530;
		constexpr auto torqueScale = 0x534;
		constexpr auto com = 0x540;
		constexpr auto killTriggers = 0x548;
		constexpr auto groundEffects = 0x550;
		constexpr auto serverGibs = 0x558;
		constexpr auto explosionEffect = 0x560;
		constexpr auto fireBall = 0x568;
		constexpr auto crashEffect = 0x570;
		constexpr auto liftDotMax = 0x578;
		constexpr auto altForceDotMin = 0x57C;
		constexpr auto liftFraction = 0x580;
		constexpr auto thrustLerpSpeed = 0x584;
		constexpr auto timeSinceUpdatedGroundEffects = 0x588;
	};
	namespace HitInfo {
		constexpr auto Initiator = 0x10;
		constexpr auto WeaponPrefab = 0x18;
		constexpr auto Weapon = 0x20;
		constexpr auto DoHitEffects = 0x28;
		constexpr auto DoDecals = 0x29;
		constexpr auto IsPredicting = 0x2A;
		constexpr auto UseProtection = 0x2B;
		constexpr auto Predicted = 0x30;
		constexpr auto DidHit = 0x38;
		constexpr auto HitEntity = 0x40;
		constexpr auto HitBone = 0x48;
		constexpr auto HitPart = 0x4C;
		constexpr auto HitMaterial = 0x50;
		constexpr auto HitPositionWorld = 0x54;
		constexpr auto HitPositionLocal = 0x60;
		constexpr auto HitNormalWorld = 0x6C;
		constexpr auto HitNormalLocal = 0x78;
		constexpr auto PointStart = 0x84;
		constexpr auto PointEnd = 0x90;
		constexpr auto ProjectileID = 0x9C;
		constexpr auto ProjectileHits = 0xA0;
		constexpr auto ProjectileDistance = 0xA4;
		constexpr auto ProjectileIntegrity = 0xA8;
		constexpr auto ProjectileTravelTime = 0xAC;
		constexpr auto ProjectileTrajectoryMismatch = 0xB0;
		constexpr auto ProjectileVelocity = 0xB4;
		constexpr auto ProjectilePrefab = 0xC0;
		constexpr auto material = 0xC8;
		constexpr auto damageProperties = 0xD0;
		constexpr auto damageTypes = 0xD8;
		constexpr auto CanGather = 0xE0;
		constexpr auto DidGather = 0xE1;
		constexpr auto gatherScale = 0xE4;
	};
	namespace System_Number {
		constexpr auto s_negCurrencyFormats = 0x8;//íå íà àâòîäàìïå
		constexpr auto s_posPercentFormats = 0x10;//íå íà àâòîäàìïå
		constexpr auto s_negPercentFormats = 0x18;//íå íà àâòîäàìïå
		constexpr auto s_negNumberFormats = 0x20;//íå íà àâòîäàìïå
		constexpr auto s_charToHexLookup = 0x28;//íå íà àâòîäàìïå
		constexpr auto s_rgval64Power10 = 0x30;//íå íà àâòîäàìïå
		constexpr auto s_rgexp64Power10 = 0x38;//íå íà àâòîäàìïå
		constexpr auto s_rgval64Power10By16 = 0x40;//íå íà àâòîäàìïå
		constexpr auto s_rgexp64Power10By16 = 0x48;//íå íà àâòîäàìïå
	};
	namespace System_Globalization_NumberFormatInfo {
		constexpr auto numberGroupSizes = 0x10;//íå íà àâòîäàìïå
		constexpr auto currencyGroupSizes = 0x18;//íå íà àâòîäàìïå
		constexpr auto percentGroupSizes = 0x20;//íå íà àâòîäàìïå
		constexpr auto positiveSign = 0x28;//íå íà àâòîäàìïå
		constexpr auto negativeSign = 0x30;//íå íà àâòîäàìïå
		constexpr auto numberDecimalSeparator = 0x38;//íå íà àâòîäàìïå
		constexpr auto numberGroupSeparator = 0x40;//íå íà àâòîäàìïå
		constexpr auto currencyGroupSeparator = 0x48;//íå íà àâòîäàìïå
		constexpr auto currencyDecimalSeparator = 0x50;//íå íà àâòîäàìïå
		constexpr auto currencySymbol = 0x58;//íå íà àâòîäàìïå
		constexpr auto ansiCurrencySymbol = 0x60;//íå íà àâòîäàìïå
		constexpr auto nanSymbol = 0x68;//íå íà àâòîäàìïå
		constexpr auto positiveInfinitySymbol = 0x70;//íå íà àâòîäàìïå
		constexpr auto negativeInfinitySymbol = 0x78;//íå íà àâòîäàìïå
		constexpr auto percentDecimalSeparator = 0x80;//íå íà àâòîäàìïå
		constexpr auto percentGroupSeparator = 0x88;//íå íà àâòîäàìïå
		constexpr auto percentSymbol = 0x90;//íå íà àâòîäàìïå
		constexpr auto perMilleSymbol = 0x98;//íå íà àâòîäàìïå
		constexpr auto nativeDigits = 0xa0;//íå íà àâòîäàìïå
		constexpr auto m_dataItem = 0xa8;//íå íà àâòîäàìïå
		constexpr auto numberDecimalDigits = 0xac;//íå íà àâòîäàìïå
		constexpr auto currencyDecimalDigits = 0xb0;//íå íà àâòîäàìïå
		constexpr auto currencyPositivePattern = 0xb4;//íå íà àâòîäàìïå
		constexpr auto currencyNegativePattern = 0xb8;//íå íà àâòîäàìïå
		constexpr auto numberNegativePattern = 0xbc;//íå íà àâòîäàìïå
		constexpr auto percentPositivePattern = 0xc0;//íå íà àâòîäàìïå
		constexpr auto percentNegativePattern = 0xc4;//íå íà àâòîäàìïå
		constexpr auto percentDecimalDigits = 0xc8;//íå íà àâòîäàìïå
		constexpr auto digitSubstitution = 0xcc;//íå íà àâòîäàìïå
		constexpr auto isReadOnly = 0xd0;//íå íà àâòîäàìïå
		constexpr auto m_useUserOverride = 0xd1;//íå íà àâòîäàìïå
		constexpr auto m_isInvariant = 0xd2;//íå íà àâòîäàìïå
		constexpr auto validForParseAsNumber = 0xd3;//íå íà àâòîäàìïå
		constexpr auto validForParseAsCurrency = 0xd4;//íå íà àâòîäàìïå
	};
	namespace TOD_AtmosphereParameters {
		constexpr auto RayleighMultiplier = 0x10;//íå íà àâòîäàìïå
		constexpr auto MieMultiplier = 0x14;//íå íà àâòîäàìïå
		constexpr auto Brightness = 0x18;//íå íà àâòîäàìïå
		constexpr auto Contrast = 0x1c;//íå íà àâòîäàìïå
		constexpr auto Directionality = 0x20;//íå íà àâòîäàìïå
		constexpr auto Fogginess = 0x24;//íå íà àâòîäàìïå
		constexpr auto validForParseAsCurrency = 0xd4;//íå íà àâòîäàìïå
	};
	namespace TOD_MoonParameters {
		constexpr auto MeshSize = 0x10;//íå íà àâòîäàìïå
		constexpr auto MeshBrightness = 0x14;//íå íà àâòîäàìïå
		constexpr auto MeshContrast = 0x18;//íå íà àâòîäàìïå
		constexpr auto HaloSize = 0x1c;//íå íà àâòîäàìïå
		constexpr auto HaloBrightness = 0x20;//íå íà àâòîäàìïå
		constexpr auto Position = 0x24;//íå íà àâòîäàìïå
	};
	namespace TOD_CloudParameters {
		constexpr auto Size = 0x10;//íå íà àâòîäàìïå
		constexpr auto Opacity = 0x14;//íå íà àâòîäàìïå
		constexpr auto Coverage = 0x18;//íå íà àâòîäàìïå
		constexpr auto Sharpness = 0x1c;//íå íà àâòîäàìïå
		constexpr auto Coloring = 0x20;//íå íà àâòîäàìïå
		constexpr auto Attenuation = 0x24;//íå íà àâòîäàìïå
		constexpr auto Saturation = 0x28;//íå íà àâòîäàìïå
		constexpr auto Brightness = 0x30;//íå íà àâòîäàìïå
	};
	namespace TOD_NightParameters {
		constexpr auto MoonColor = 0x10;//íå íà àâòîäàìïå
		constexpr auto LightColor = 0x18;//íå íà àâòîäàìïå
		constexpr auto RayColor = 0x20;//íå íà àâòîäàìïå
		constexpr auto SkyColor = 0x28;//íå íà àâòîäàìïå
		constexpr auto CloudColor = 0x30;//íå íà àâòîäàìïå
		constexpr auto FogColor = 0x38;//íå íà àâòîäàìïå
		constexpr auto AmbientColor = 0x40;//íå íà àâòîäàìïå
		constexpr auto LightIntensity = 0x48;//íå íà àâòîäàìïå
		constexpr auto ShadowStrength = 0x4c;//íå íà àâòîäàìïå
		constexpr auto AmbientMultiplier = 0x50;//íå íà àâòîäàìïå
		constexpr auto ReflectionMultiplier = 0x54;//íå íà àâòîäàìïå
	};
}







namespace CO
{
	constexpr auto IsDucked = 0x95C820; // BasePlayer IsDucked
	constexpr auto GetGameObjectComponent = 0x2E7E2E0; //+ Dumper::GetMethodOffset("UnityEngine.CoreModule", "UnityEngine", "GameObject", "GetComponent", 1)))(pointer, type);
	constexpr auto GUIDToObject = 0xA4D950; //+ Dumper::GetMethodOffset("Assembly-CSharp", "", "GameManifest", "GUIDToObject", 1)))(guid);
	// script.json
	constexpr auto TodSky = 61917176; // TOD_Sky_c* || TOD_Sky_TypeInfo
}